{{- if include "certmate.generatesSecret" . }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "certmate.secretName" . }}
  labels: {{- include "certmate.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{- if .Values.secrets.apiBearerToken }}
  API_BEARER_TOKEN: {{ .Values.secrets.apiBearerToken | quote }}
  {{- end }}
  {{- if .Values.secrets.secretKey }}
  SECRET_KEY: {{ .Values.secrets.secretKey | quote }}
  {{- end }}
  {{- range $k, $v := .Values.secrets.extra }}
  {{ $k }}: {{ $v | quote }}
  {{- end }}
{{- end }}
