"""A new endpoint must move the contract version, and something must check.

`API_CONTRACT_VERSION` exists so a client can ask "will my client still work"
without reading the release number, and the rule for moving it is written
beside the constant: a new endpoint is a MINOR, a removed one is a MAJOR.

`POST /api/client-certs/ca/reset` shipped without moving it at all. The
surface grew by one endpoint and the version a client polls stayed at 2.2, so
the one number that exists to describe the surface described the surface
before it. Nothing compared the two: tests/test_the_contract_says_when_it_
changes.py checks that the constant exists, looks like a version, is sent on
every response and has its rule written down, which is everything about the
number except whether it is the right one.

This file records the surface the current version describes, and fails when
the tree and the record disagree. It is a snapshot, not a derivation: the point
is that changing the surface makes you open the file where the version is
written down, next to a message that says which way to move it.

The snapshot is tests/api_contract_surface.json and it carries both
halves, the version and the routes, because either alone proves nothing. It is
regenerated by running this file's `current_surface` fixture and writing it
out; there is no magic to it.

It sits directly in tests/ rather than in tests/data/ because .gitignore
carries an unanchored `data/` rule, meant for the application's runtime
directory, which hides any directory of that name anywhere in the tree. A
snapshot git cannot see is a snapshot that proves nothing.

`/api/web/` is excluded for the same reason it is excluded from
tests/test_the_api_surface_is_documented.py: those are the dashboard's own
calls, outside the flask-restx surface that becomes /api/swagger.json, and a
client is not meant to build against them. Adding one is not a contract change.
"""
import json
import pathlib
import re
import secrets

import pytest

from modules.core.constants import API_CONTRACT_VERSION

pytestmark = [pytest.mark.unit]

REPO = pathlib.Path(__file__).resolve().parent.parent
SNAPSHOT = REPO / 'tests' / 'api_contract_surface.json'
INTERNAL_PREFIX = '/api/web/'


@pytest.fixture(scope='module')
def current_surface():
    """Every verb+path pair the app serves under /api/, bar the dashboard's."""
    import tempfile

    root = pathlib.Path(tempfile.mkdtemp()) / 'certmate'
    module_dir = root / 'modules' / 'core'
    module_dir.mkdir(parents=True)
    anchor = module_dir / 'factory.py'
    anchor.write_text('# test path anchor\n', encoding='utf-8')

    with pytest.MonkeyPatch.context() as patch:
        patch.setenv('TESTING', 'true')
        patch.setenv('FLASK_ENV', 'testing')
        patch.setenv('API_BEARER_TOKEN', secrets.token_urlsafe(32))
        from modules.core.factory import create_app
        patch.setattr('modules.core.factory.__file__', str(anchor))
        result = create_app()
    app = result[0] if isinstance(result, tuple) else result

    surface = set()
    for rule in app.url_map.iter_rules():
        path = str(rule)
        if not path.startswith('/api/') or path.startswith(INTERNAL_PREFIX):
            continue
        path = re.sub(r'<[^>]+>', '<X>', path).rstrip('/') or '/'
        for verb in rule.methods:
            if verb not in ('HEAD', 'OPTIONS'):
                surface.add(f'{verb} {path}')
    return surface


@pytest.fixture(scope='module')
def snapshot():
    return json.loads(SNAPSHOT.read_text(encoding='utf-8'))


def test_the_recorded_surface_is_the_one_the_app_serves(current_surface, snapshot):
    recorded = set(snapshot['surface'])
    added = sorted(current_surface - recorded)
    removed = sorted(recorded - current_surface)

    message = []
    if added:
        message.append(
            'These endpoints exist and the recorded surface does not have '
            'them. A new endpoint is a MINOR bump of API_CONTRACT_VERSION '
            '(the rule is beside the constant in modules/core/constants.py). '
            'Move the version, write the history line, and update '
            f'{SNAPSHOT.relative_to(REPO)}:\n  ' + '\n  '.join(added))
    if removed:
        message.append(
            'These endpoints are recorded and no longer exist. A removed '
            'endpoint is a MAJOR bump, and removing one without deprecating '
            'it first is what the Deprecation/Sunset mechanism in '
            'modules/api/deprecation.py is for:\n  ' + '\n  '.join(removed))

    assert not message, '\n\n'.join(message)


def test_the_recorded_version_is_the_one_the_app_sends(snapshot):
    """The snapshot describes a specific contract version, and says which.

    Recording the routes without the version would leave a file that says what
    the surface is and not what it is the surface OF, which is the half that
    makes the rule enforceable.
    """
    assert snapshot['contract_version'] == API_CONTRACT_VERSION, (
        f'{SNAPSHOT.relative_to(REPO)} records contract '
        f'{snapshot["contract_version"]} and the app sends '
        f'{API_CONTRACT_VERSION}. Whichever moved, the other has to follow in '
        f'the same commit.'
    )


def test_the_surface_is_not_empty(current_surface):
    """CONTROL for the instrument. A fixture that stopped building the app, or
    a prefix filter that stopped matching, would compare two empty sets and
    pass while proving nothing."""
    assert len(current_surface) > 80, (
        f'only {len(current_surface)} verb+path pairs found under /api/, '
        f'which cannot be true of this application'
    )
