"""The published API contract must describe the response the app actually sends.

CertMate serves an OpenAPI document at /api/swagger.json, generated by
flask-restx from the models in modules/api/models.py. That document is what an
integrator reads, and it is only as good as the models: a field the code
returns and the model omits is invisible to every client that was written from
the contract.

It happened on the release that bumped API_CONTRACT_VERSION to 2.2 *because*
two fields were added. `expired` and `seconds_left` went into
`_parse_certificate_info` and not into the Certificate model, so the published
contract described a response missing exactly the two fields the version bump
announced (#829). modules/api/models.py already carried a comment about the
previous time this class of drift shipped.

Comparing the two by hand is the thing that failed. This asks the code for the
keys it returns and the model for the keys it declares, and requires the first
to be a subset of the second.
"""
import datetime

import pytest
from cryptography import x509
from cryptography.hazmat.primitives import hashes, serialization
from cryptography.hazmat.primitives.asymmetric import rsa
from cryptography.x509.oid import NameOID

from modules.core.certificates import CertificateManager

pytestmark = [pytest.mark.unit]


class _Settings:
    def load_settings(self):
        return {}

    def get_domain_dns_provider(self, domain, settings):
        return 'cloudflare'


def _certificate_pem(days_valid=30):
    key = rsa.generate_private_key(public_exponent=65537, key_size=2048)
    name = x509.Name([x509.NameAttribute(NameOID.COMMON_NAME, 'abc.local')])
    now = datetime.datetime.now(datetime.timezone.utc)
    cert = (x509.CertificateBuilder()
            .subject_name(name).issuer_name(name)
            .public_key(key.public_key())
            .serial_number(x509.random_serial_number())
            .not_valid_before(now - datetime.timedelta(days=1))
            .not_valid_after(now + datetime.timedelta(days=days_valid))
            .sign(key, hashes.SHA256()))
    return cert.public_bytes(serialization.Encoding.PEM)


@pytest.fixture(scope='module')
def certificate_model_fields():
    """The field names the Certificate model publishes in the contract."""
    from flask import Flask
    from flask_restx import Api

    from modules.api.models import create_api_models

    app = Flask(__name__)
    api = Api(app)
    models = create_api_models(api)
    model = models.get('certificate_model') or models.get('certificate')
    assert model is not None, (
        f'create_api_models no longer returns a certificate model; it returns '
        f'{sorted(models)}. This check compares against that model, so a rename '
        f'must be followed here rather than silently passing over nothing.'
    )
    return set(model.keys())


def _returned_keys():
    """Every key the certificate-info path can return, across its branches."""
    manager = CertificateManager.__new__(CertificateManager)
    manager.settings_manager = _Settings()
    parsed = manager._parse_certificate_info('abc.local', _certificate_pem())
    # The branch taken when the certificate is present but unparseable: its
    # shape must be described too, and it is the branch that produced the
    # original null-handling defect.
    unparseable = manager._parse_certificate_info('abc.local', b'not a cert')
    empty = manager._create_empty_cert_info('abc.local')
    return set(parsed) | set(unparseable) | set(empty)


def test_the_model_is_being_read(certificate_model_fields):
    assert len(certificate_model_fields) >= 15, (
        f'the Certificate model declares {len(certificate_model_fields)} '
        f'fields; the shape changed and the comparison below would pass over '
        f'almost nothing.'
    )


def test_every_field_the_code_returns_is_in_the_published_contract(
        certificate_model_fields):
    returned = _returned_keys()
    undeclared = sorted(returned - certificate_model_fields)
    assert not undeclared, (
        'these fields are returned by the certificate-info path and are not in '
        'the Certificate model, so /api/swagger.json does not mention them and '
        f'a client written from the contract cannot know they exist: {undeclared}'
    )


def test_the_three_branches_agree_on_their_shape():
    """A client should not have to know which branch answered it.

    The parsed branch, the unparseable branch and the no-certificate branch
    used to return different key sets, so `expired` was present or absent
    depending on a failure the caller cannot see.
    """
    manager = CertificateManager.__new__(CertificateManager)
    manager.settings_manager = _Settings()
    parsed = set(manager._parse_certificate_info('abc.local', _certificate_pem()))
    unparseable = set(manager._parse_certificate_info('abc.local', b'not a cert'))
    for field in ('days_left', 'days_until_expiry', 'expired', 'seconds_left',
                  'needs_renewal', 'private_key_state'):
        assert field in parsed, f'{field} missing from the parsed branch'
        assert field in unparseable, f'{field} missing from the unparseable branch'
